spring:
 application:
  name: song-Service

 datasource:
  url: jdbc:postgresql://localhost:5433/songdb
  username: postgres
  password: password
  driver-class-name: org.postgresql.Driver
  hikari:
    initialization-fail-timeout: 5000
 
 jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

 kafka:
   bootstrap-servers: localhost:9092
   consumer:
     group-id: song-service-group
     auto-offset-reset: earliest
     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     properties:
       spring.json.trusted.packages: "*"
   producer:
     key-serializer: org.apache.kafka.common.serialization.StringSerializer
     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

aws:
  bucket:
    name: hars-demo-v1
  region: ap-south-1

 